export const GET_BOOK_START = "GET_BOOK_START";
export const GET_BOOK_END = "GET_BOOK_END";
export const GET_BOOK_SUCCESS = "GET_BOOK_SUCCESS";
export const GET_BOOK_FAILURE = "GET_BOOK_FAILURE";

export const CREATE_BOOK_START = "CREATE_BOOK_START";
export const CREATE_BOOK_END = "CREATE_BOOK_END";
export const CREATE_BOOK_SUCCESS = "CREATE_BOOK_SUCCESS";
export const CREATE_BOOK_FAILURE = "CREATE_BOOK_FAILURE";

export const EDIT_BOOK_START = "EDIT_BOOK_START";
export const EDIT_BOOK_END = "EDIT_BOOK_END";
export const EDIT_BOOK_SUCCESS = "EDIT_BOOK_SUCCESS";
export const EDIT_BOOK_FAILURE = "EDIT_BOOK_FAILURE";

export const GET_SINGLE_BOOK_START = "GET_SINGLE_BOOK_START";
export const GET_SINGLE_BOOK_END = "GET_SINGLE_BOOK_END";
export const GET_SINGLE_BOOK_SUCCESS = "GET_SINGLE_BOOK_SUCCESS";
export const GET_SINGLE_BOOK_FAILURE = "GET_SINGLE_BOOK_FAILURE";

export const DELETE_BOOK_START = "DELETE_BOOK_START";
export const DELETE_BOOK_END = "DELETE_BOOK_END";
export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS";
export const DELETE_BOOK_FAILURE = "DELETE_BOOK_FAILURE";

export const CLEAR_BOOK_STORE = "CLEAR_BOOK_STORE";
