export const GET_EVENT_START = "GET_EVENT_START";
export const GET_EVENT_END = "GET_EVENT_END";
export const GET_EVENT_SUCCESS = "GET_EVENT_SUCCESS";
export const GET_EVENT_FAILURE = "GET_EVENT_FAILURE";

export const CREATE_EVENT_START = "CREATE_EVENT_START";
export const CREATE_EVENT_END = "CREATE_EVENT_END";
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
export const CREATE_EVENT_FAILURE = "CREATE_EVENT_FAILURE";

export const EDIT_EVENT_START = "EDIT_EVENT_START";
export const EDIT_EVENT_END = "EDIT_EVENT_END";
export const EDIT_EVENT_SUCCESS = "EDIT_EVENT_SUCCESS";
export const EDIT_EVENT_FAILURE = "EDIT_EVENT_FAILURE";

export const GET_SINGLE_EVENT_START = "GET_SINGLE_EVENT_START";
export const GET_SINGLE_EVENT_END = "GET_SINGLE_EVENT_END";
export const GET_SINGLE_EVENT_SUCCESS = "GET_SINGLE_EVENT_SUCCESS";
export const GET_SINGLE_EVENT_FAILURE = "GET_SINGLE_EVENT_FAILURE";

export const DELETE_EVENT_START = "DELETE_EVENT_START";
export const DELETE_EVENT_END = "DELETE_EVENT_END";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_FAILURE = "DELETE_EVENT_FAILURE";

export const CLEAR_EVENT_STORE = "CLEAR_EVENT_STORE";
