export const CREATE_USER_START = "SIGNUP_USER_START";
export const CREATE_USER_END = "SIGNUP_USER_END";
export const CREATE_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const CREATE_USER_FAILURE = "SIGNUP_USER_FAILURE";

export const LOGIN_USER_START = "LOGIN_USER_START";
export const LOGIN_USER_END = "LOGIN_USER_END";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const LOGOUT_USER_START = "LOGOUT_USER_START";
export const LOGOUT_USER_END = "LOGOUT_USER_END";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILURE = "LOGOUT_USER_FAILURE";

export const GET_USERS_START = "GET_USERS_START";
export const GET_USERS_END = "GET_USERS_END";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILURE = "GET_USERS_FAILURE";
